name: telegram_mini_app
description: Simple library for build telegram mini app(web app) with Flutter easier.
version: 0.0.2
homepage: https://github.com/tiendungtsptvn/telegram_mini_app

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

screenshots:
  - description: "© Telegram"
    path: assets/logo.webp

topics:
  - telegram
  - mini-app
  - web-app

flutter:



